name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login docker hub
      env:
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      # 指定login命令登录hub.docker.com，帐号和密码已经在GitHub网页中配置好了
      run: |
        echo "${DOCKERHUB_TOKEN}" | docker login --username ${DOCKERHUB_USER} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ideploy/getimer:latest  
    - name: Pull from QCloud
      run: docker pull ccr.ccs.tencentyun.com/wlniao/getimer && docker tag  ccr.ccs.tencentyun.com/wlniao/getimer ideploy/getimer

      
    - name: Push to DockerHub
      run: docker push ideploy/getimer
